version: '3.8'

services:
  uptime-kuma-suite:
    # 从当前目录的 Dockerfile 构建镜像
    build: .
    # 为构建好的镜像命名
    image: my-ultimate-uptime-kuma
    # 容器名称
    container_name: uptime-kuma-suite
    # 集成重启策略
    restart: unless-stopped
    # 持久化 Uptime Kuma 的数据
    volumes:
      - uptime-kuma-data:/app/data
    # 更新 environment 部分
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      # 新增 Telegram 环境变量
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      # 您也可以在这里添加邮件相关的环境变量
      # - SMTP_SERVER=${SMTP_SERVER}
      # - SMTP_PORT=${SMTP_PORT}
      # ...
    cap_add:
      - SYS_ADMIN

volumes:
  uptime-kuma-data:
